
image_path: [
  "data/ani-pic/71.png",
  "data/ani-pic/112.png",
  "data/ani-pic/74.png",
  #"data/ani-pic/77.png", ###
  "data/ani-pic/83.png", #####*****
  "data/ani-pic/87.png",
  "data/ani-pic/61.png",
  "data/ani-pic/94.png",
  #"data/ani-pic/97.png", ###
  "data/ani-pic/104.png", #####*****
  "data/ani-pic/115.png",
  "data/ani-pic/70.png",
  #"data/ani-pic/66.png", ###
  "data/ani-pic/118.png",
  "data/ani-pic/120.png", #####*****
  "data/ani-pic/127.png", 
  "data/ani-pic/121.png",
  "data/ani-pic/129.png",
  "data/ani-pic/128.png",
  "data/ani-pic/125.png", #####*****
  "data/ani-pic/135.png",
  "data/ani-pic/148.png",
  "data/ani-pic/146.png",
  "data/ani-pic/171.png", 
  "data/ani-pic/136.png", #####*****
  "data/ani-pic/149.png",
  "data/ani-pic/132.png",
  "data/ani-pic/158.png",
  "data/ani-pic/141.png", 
  "data/ani-pic/161.png", #####*****
  "data/ani-pic/144.png",
  "data/ani-pic/169.png",
  "data/ani-pic/154.png",
  "data/ani-pic/165.png",
  "data/ani-pic/172.png", #####*****
  "data/ani-pic/173.png", 
]

character_name: [
  "Albedo",
  "Elysia",
  "Yae Miko",
  #"Diluc", ###
  "Gan Yu",                #####*****
  "Hu Tao",
  "Raiden Shogun",
  "Lisa",
  #"Nahida", ###
  "Aventurine",           #####*****
  "Sucrose",
  "Sangonomiya Kokomi",
  #"Kamisato Ayaka", ###
  "Yoimiya",
  "Ye Lan",                #####*****
  "Bei Dou",
  "Dan Heng",
  "Faruzan",
  "Kamisato Ayato",
  "Sayu",                 #####*****
  "Amber",
  "Barbara",
  "Bennett",
  "Tartaglia",
  "Kaedehara Kazuha",     #####*****
  "Arataki Itto",
  "Ning Guang",
  "Noelle",
  "Paimon",
  "Kamisato Ayaka",       #####*****
  "Venti",
  "Xiao",
  "Xing Qiu",
  "Zhong Li",
  "Diluc",                #####*****
  "Nahida",
]

character_name_dict: {
  "Albedo": "阿贝多",
  "Elysia": "爱莉希雅",
  "Yae Miko": "八重神子",
  #"Diluc": "迪卢克", ###
  "Gan Yu": "甘雨",                #####*****
  "Hu Tao": "胡桃",
  "Raiden Shogun": "雷电将军",
  "Lisa": "丽莎",
  #"Nahida": "纳西妲", ###
  "Aventurine": "砂金",           #####*****
  "Sucrose": "砂糖",
  "Sangonomiya Kokomi": "珊瑚宫心海",
  #"Kamisato Ayaka": "神里绫华", ###
  "Yoimiya": "霄宫",
  "Ye Lan": "夜兰",                #####*****
  "Bei Dou": "北斗",
  "Dan Heng": "丹恒",
  "Faruzan": "珐露珊",
  "Kamisato Ayato": "神里绫人",
  "Sayu": "早柚",                 #####*****
  "Amber": "安柏",
  "Barbara": "芭芭拉",
  "Bennett": "班尼特",
  "Tartaglia": "达达利亚",
  "Kaedehara Kazuha": "枫原万叶",     #####*****
  "Arataki Itto": "荒泷一斗",
  "Ning Guang": "凝光",
  "Noelle": "诺艾尔",
  "Paimon": "派蒙",
  "Kamisato Ayaka": "神里绫华",       #####*****
  "Venti": "温迪",
  "Xiao": "魈",
  "Xing Qiu": "行秋",
  "Zhong Li": "钟离",
  "Diluc": "迪卢克",                #####*****
  "Nahida": "纳西妲",
}