1011:
  - 安比
  - Anby
  - 安笔
1021:
  - 猫猫
  - Nekomata
  - 猫妖
  - 猫怪
  - 猫鼬
  - 猫宫 又奈
  - 猫宫又奈
  - 又奈
  - Neko
  - neko
1031:
  - 妮可
  - Nicole
  - 尼克
  - 妮克
  - 妮寇
  - 妮可·德玛拉
  - 妮可德玛拉
1041:
  - 十一号
  - Soldier 11
  - 十一
  - 11号
  - '11'
  - 「11号」
  - 玛卡巴卡
  - 火刀
1061:
  - 可琳
  - Corin
  - 克林
  - 柯林
  - 可林
1071:
  - 凯撒
  - Caesar
1081:
  - 比利
  - Billy
  - 比例
  - bili
  - 比利·奇德
  - 比利奇德
1101:
  - 珂蕾妲
  - Koleda
  - 柯雷妲
  - 珂雷哒
  - 柯蕾妲
  - 锤妹
1111:
  - 安东
  - Anton
  - 安东·伊万诺夫
  - 安东伊万诺夫
1121:
  - 本
  - Ben
  - 熊本
  - 熊本熊
  - ben
  - 比格
  - 本·比格
  - 本比格
  - 大本
  - 熊哥
1131:
  - 苍角
  - Soukaku
  - 苍绝
  - 仓角
  - 仓脚
1141:
  - 莱卡恩
  - Lycaon
  - 冯·莱卡恩
  - 冯莱卡恩
  - 狼哥
1151:
  - 露西
  - Lucy
  - 路西
  - 露西亚娜·德·蒙特夫
  - 露西亚娜德蒙特夫
  - 露西亚娜
  - 鲁西
1161:
  - 莱特
  - Lighter
  - 赖特
1171:
  - 柏妮思
  - Burnice
1181:
  - 格莉丝
  - Grace
  - 格利斯
  - 格莉丝·霍华德
  - 格莉丝霍华德
1191:
  - 艾莲
  - Ellen
  - 爱莲
  - 爱怜
  - 艾莲·乔
  - 艾莲乔
  - 鲨鱼妹
  - 鲨鱼


1211:
  - 丽娜
  - Rina
  - 莉娜
  - 李娜
  - 亚历山德丽娜·莎芭丝缇安
  - 亚历山德丽娜莎芭丝缇安
  - rina
1241:
  - 朱鸢
  - Zhu Yuan
  - 朱元
  - 警员


雅:
  - 星见雅
  - 星见

悠真:
  - 悠
  - 浅羽悠真
  - 浅羽
1221:
  - 月城柳
  - Yanagi
  - 月城
1251:
  - 青衣
  - Qingyi
  - 青医
1271:
  - 赛斯
  - Seth
  - 赛斯·洛威尔
  - 赛斯洛威尔
  - 塞斯
  - 洛威尔
1261:
  - 简
  - Jane
1281:
  - 派派
  - Piper
  - 拍拍
  - 韦尔
  - 派派·韦尔
  - 派派韦尔

哲:
  - 哲
铃:
  - 铃